---
title: "p8105_hw5_gx2144"
author: "Guangling Xu"
date: "2019/11/1"
output: github_document
---
## Problem 1

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```
## filling missing values

```{r filling missing values}
check = function(x) {
  
  if (is.numeric(x)) {
    x = replace_na(x, round(mean(x, na.rm = TRUE), digits = 2))
  } else if (is.character(x)) {
    x = replace_na(x, "virginica")
  }
  x 
}

output = map(iris_with_missing, check) %>% 
bind_cols()

```


## Problem 2 

```{r}
names = list.files(path = "./data/hw5_data/data")

read_data = function(x){
  path = str_c("./data/hw5_data/data/",x)
  read.csv(path)
}

mergedata = map(names, read_data) %>% 
  bind_rows() %>% 
  janitor::clean_names() %>% 
  mutate(
    file_names = names
  ) %>% 
  separate(file_names, into = c("Group", "ID"), sep = "_") %>% 
  mutate(
    ID = str_remove(ID, ".csv")
    ) %>% 
  select(Group, ID, everything())
 
```
 
## Make a spaghetti plot
```{r}
tidy_mergedata = 
  pivot_longer(
    mergedata, 
    week_1:week_8,
    names_to = "Week", 
    names_prefix = "week_",
    values_to = "Value") %>% 
  mutate(
    Group = recode(Group, con = "Control Group", exp = "Experiment Group")
  )
  
ggplot(tidy_mergedata,aes(x = Week,y = Value))+
    geom_line(aes(group = ID, color = ID)) + 
    theme_set(theme_minimal() + 
    theme(legend.position = "bottom"))+       
    facet_grid(.~Group)+
  labs(
    title = "Spaghetti Plot Showing Observations On Each Subject Over Time"
  )
```
  
  
##Problem 3

```{r}
sim_regression = function(beta1) {
  
  sim_data = tibble(
    x = rnorm(30, mean = 0, sd = 1),
    y = 2 + beta1 * x + rnorm(30, 0, 50)
  )
  
  ls_fit = lm(y ~ x, data = sim_data) %>% 
  broom::tidy()
  
  tibble(
    beta1_hat = pull(ls_fit,estimate)[2],
    p_value = pull(ls_fit,p.value)[2]
  )
}

sim_results = 
  rerun(10000, sim_regression(0)) %>% 
  bind_rows()
```


### Dataset When beta = 1-6
```{r}

simulate_n_regressions = 
  function(n_runs = 10000,beta1) 
  {rerun(n_runs, sim_regression(beta1)) %>% 
    bind_rows()
  }


sim_results2 = 
  tibble(beta1 = c(1, 2, 3, 4, 5, 6)) %>% 
  mutate(
    estimate_dfs = map(.x = beta1, ~simulate_n_regressions(n_runs = 10000, beta1 = .x))
  ) %>% 
  unnest %>% 
  unnest
```


### Make a Plot reporting the proportion of times the null was rejected 
```{r}
plot1 = sim_results2 %>% 
  filter(p_value < 0.05) %>% 
  group_by(beta1) %>% 
  summarise(
    power = n()/10000
  ) 

ggplot(plot1, aes(x = beta1,y = power))+
  geom_point()+
  geom_line()+
  labs(
    title = "Association Between True Beta 1 and Power",
    x = "True Beta 1",
    y = "Power"
  )

```

* comment
From the plot we can see that Power increases as True Beta1 increases.There is a positive relationship between True Beta1 and Power. 

### Plot of Average of Estimated Beta and True value of Beta
```{r}
plot2 = sim_results2 %>%
  group_by(beta1) %>% 
  summarize(
    mean1 = mean(beta1_hat)
  )

plot3 = sim_results2 %>% 
  filter(p_value < 0.05) %>% 
  group_by(beta1) %>% 
  summarize(
    mean2 = mean(beta1_hat)
  )

binddata = left_join(plot2, plot3)

ggplot(binddata, aes(x = beta1))+
  geom_point(aes(y = mean1))+
  geom_line(aes(y = mean1, color = "red"))+
  geom_point(aes(y = mean2))+
  geom_line(aes(y = mean2,color = "blue"))+
  scale_colour_discrete(labels = c('Average Estimate When Null was rejected','Average Estimate '))+
  labs(
    title = "Association Between Average Estimate Beta 1 and True Beta 1",
    x = "True Beta 1",
    y = "Average Estimate Beta 1"
  )

```

